import React from 'react';
import {
    Container, 
    Top, 
    BarContainer, 
    EmptyBar, 
    FillBar, 
    Star, 
    Total,
    Exchanges, 
    LeftExchanges,
    AmountLeftExchanges,
    TextLeftExchanges,
    RightExchanges,
    AmountRightExchanges,
    TextRightExchanges,
    Bottom,
    Title,
    Description,
    ImagesContainer,
    ImageContainer,
    Image,
    SocialsWebs,
    SocialWeb,
    SocialWebTitle,
    SocialWebText
} from './styled';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome'
import { faStar } from '@fortawesome/free-solid-svg-icons'
import Icon from '../../../../assets/icon.png';

export default Profile = ({currentState = 0, pos = 0}) => {
    return (
        <Container
            currentState={currentState}
            pos={pos}
        >
            <Top>
                <BarContainer>
                    <EmptyBar>
                        <FillBar/>
                        <Star>
                            <FontAwesomeIcon 
                                icon={faStar}
                                size={50}
                            />
                            <Total>
                                12
                            </Total>
                        </Star>
                    </EmptyBar>
                </BarContainer> 
                <Exchanges>
                    <LeftExchanges>
                        <AmountLeftExchanges>
                            7
                        </AmountLeftExchanges>
                        <TextLeftExchanges>
                            Intercambios ofrecidos
                        </TextLeftExchanges>
                    </LeftExchanges>
                    <RightExchanges>
                        <AmountRightExchanges>
                            12
                        </AmountRightExchanges>
                        <TextRightExchanges>
                            Intercambios realizados
                        </TextRightExchanges>
                    </RightExchanges>
                </Exchanges>
            </Top>
            <Bottom>
                <Title>
                    Descripción
                </Title>
                <Description>
                    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.
                </Description>
                <Title>
                    Intereses
                </Title>
                <ImagesContainer>
                    <ImageContainer>
                        <Image
                            source={Icon}
                            resizeMode='stretch'
                        />
                    </ImageContainer>
                    <ImageContainer>
                        <Image
                            source={Icon}
                            resizeMode='stretch'
                        />
                    </ImageContainer>
                    <ImageContainer>
                        <Image
                            source={Icon}
                            resizeMode='stretch'
                        />
                    </ImageContainer>
                    <ImageContainer>
                        <Image
                            source={Icon}
                            resizeMode='stretch'
                        />
                    </ImageContainer>
                    <ImageContainer>
                        <Image
                            source={Icon}
                            resizeMode='stretch'
                        />
                    </ImageContainer>
                    <ImageContainer>
                        <Image
                            source={Icon}
                            resizeMode='stretch'
                        />
                    </ImageContainer>
                </ImagesContainer>
                <Title>
                    Me puedes encontrar también en...
                </Title>
                <SocialsWebs>
                    <SocialWeb>
                        <SocialWebTitle>
                            Instagram:
                        </SocialWebTitle>
                        <SocialWebText>
                            ofijrtoñgifjewgñnjoñiwj
                        </SocialWebText>
                    </SocialWeb>
                    <SocialWeb>
                        <SocialWebTitle>
                            Facebook:
                        </SocialWebTitle>
                        <SocialWebText>
                            fjw´ñrjogñirnjwgfñoignrtñgnteogñintoginrtogin
                        </SocialWebText>
                    </SocialWeb>
                    <SocialWeb>
                        <SocialWebTitle>
                            LinkedIn:
                        </SocialWebTitle>
                        <SocialWebText>
                            aewdfjiewhfurluihneinforefrefre
                        </SocialWebText>
                    </SocialWeb>
                </SocialsWebs>
            </Bottom>
        </Container>
    )
}